name: Node CI

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

  node:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/setup-node@v1
      - name: npm install
        run: npm ci

  linting:
    runs-on: ubuntu-latest
    needs: node

    steps:
      - name: lint js
        run: npm run lint:js
      - name: lint css
        run: npm run lint:css

  export:
    runs-on: ubuntu-latest
    needs: linting

    steps:
      - name: export
        run: npm run export

  lint-html:
    runs-on: ubuntu-latest
    needs: export

    steps:
      - name: lint html
        run: npm run lint:html

  minify-html:
    runs-on: ubuntu-latest
    needs: lint-html

    steps:
      - name: minify html
        run: npm run minify-html
