name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: npm install
        run: npm ci
      - name: lint js
        run: npm run lint:js
      - name: lint css
        run: npm run lint:css
      - name: export
        run: npm run export
      - name: lint html
        run: npm run lint:html
      - name: minify html
        run: npm run minify-html
